name: 🤖 Agent Task
description: Submit a task for the AI agent
title: "[AGENT]: "
labels: ["agent:queued"]
body:
  - type: dropdown
    id: task-type
    attributes:
      label: Task Type
      options:
        - "Code Analysis"
        - "Documentation"
        - "Bug Fix"
        - "Feature Request"
        - "General Question"
        - "Research"
        - "Other"
      default: 4
    validations:
      required: true

  - type: textarea
    id: prompt
    attributes:
      label: What would you like me to do?
      description: "Describe your request. You can include file paths, URLs, or paste images."
      placeholder: "Example: Analyze the performance issues in src/main.py, or What's the best way to implement authentication?"
    validations:
      required: true